kind: AdaptiveDialog
beginDialog:
  kind: OnRedirect
  id: main
  actions:
    - kind: SendActivity
      id: sendActivity_GcgER8
      activity: I'm going to wrap everything up now...

    - kind: SetVariable
      id: setVariable_MFRNCt
      variable: Topic.userData
      value: |-
        ={  
            aad_id: System.User.Id,
            display_name: System.User.DisplayName,
            email: System.User.Email,
            timezone: System.Conversation.LocalTimeZone
        }

    - kind: SetVariable
      id: setVariable_EgQH1D
      variable: Topic.preConfiguredMeeting
      value: |-
        ={
            meetingId: Global.selectedMeeting.id,
            meetingName: Global.selectedMeeting.DisplayName,
            tier: Global.selectedTier,
            tierId: Global.selectedTierId,
            tierDescription: Global.selectedTierDescription,
            userStatus: Global.selectedMeetingStatus,
            recurringMeetingStartDate: Global.selectedMeeting.recurrenceStart, 
            recurringMeetingEndDate: Global.selectedMeeting.recurrenceEnd,
            recurrencePattern: Global.selectedMeeting.recurrencePattern,
            nextOccurrenceDate: ""
        }

inputType: {}
outputType: {}